import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

async function seed() {
  // Clean existing data
  await db.property.deleteMany()

  const properties = [
    {
      title: "Terreno Comercial Saneado - Ica Centro",
      slug: "terreno-comercial-saneado-ica-centro",
      description: "Terreno de 480m² con toda la documentación legal al día. Certificado de búsqueda negativo, sin cargas ni gravámenes. Ubicado en zona de alta demanda comercial a 2 cuadras del parque principal. Ideal para desarrollo mixto.",
      operationType: "venta",
      propertyType: "terreno",
      department: "Ica",
      province: "Ica",
      district: "Ica",
      address: "Av. Municipal 450, Ica",
      latitude: -14.0650,
      longitude: -75.7289,
      zone: "Centro Comercial Ica",
      areaTotal: 480,
      price: 285000,
      precioM2: 593.75,
      trustScore: 92,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas ni gravámenes",
      impuestoPredial: 1200,
      certificadoBusqueda: "Negativo - Sin afectaciones",
      comparisonMarket: -8.5,
      urbanServices: JSON.stringify({ agua: "Factible", luz: "Conexión existente", desague: "Factible", internet: "Fibra óptica disponible" }),
      areaFront: 20,
      materialConstruccion: null,
      imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
        "https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=800&q=80"
      ]),
      droneVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      features: JSON.stringify(["Cerca al centro", "Esquina", "Frente amplio", "Zona comercial"]),
      featured: true,
      active: true,
    },
    {
      title: "Casa Moderna 3 Dormitorios - San Isidro",
      slug: "casa-moderna-3-dormitorios-san-isidro",
      description: "Casa de 180m² construidos en 240m² de terreno. 3 dormitorios, 2 baños, estacionamiento para 2 autos. Construcción de concreto armado, acabados de primera. Certificado de búsqueda sin observaciones. Impuesto predial al día.",
      operationType: "venta",
      propertyType: "casa",
      department: "Lima",
      province: "Lima",
      district: "San Isidro",
      address: "Av. Los Incas 1234, San Isidro",
      latitude: -12.0974,
      longitude: -77.0346,
      zone: "Residencial San Isidro",
      areaTotal: 240,
      areaBuilt: 180,
      price: 850000,
      precioM2: 4722.22,
      trustScore: 97,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas",
      impuestoPredial: 4800,
      certificadoBusqueda: "Negativo",
      comparisonMarket: 3.2,
      urbanServices: JSON.stringify({ agua: "SEDAPAL", luz: "Luz del Sur", desague: "SEDAPAL", internet: "Claro/Telmex fibra" }),
      dormitorios: 3,
      banos: 2,
      estacionamiento: 2,
      pisos: 2,
      anoConstruccion: 2019,
      materialConstruccion: "concreto",
      imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"
      ]),
      features: JSON.stringify(["Concreto armado", "Estacionamiento 2 autos", "Patio interior", "Seguridad 24h"]),
      featured: true,
      active: true,
    },
    {
      title: "Terreno Agrícola con Factibilidad - Nazca",
      slug: "terreno-agricola-factibilidad-nazca",
      description: "Terreno agrícola de 2000m² con factibilidad de uso residencial. Actualmente con cultivo activo. Se requiere cambio de zonificación para uso urbano. Proceso estimado: 6-8 meses. Certificado de posesión tramitado.",
      operationType: "venta",
      propertyType: "terreno",
      department: "Ica",
      province: "Nazca",
      district: "Nazca",
      address: "Carretera Panamericana Sur Km 440",
      latitude: -14.8390,
      longitude: -75.1130,
      zone: "Zona Agrícola Nazca",
      areaTotal: 2000,
      price: 120000,
      precioM2: 60,
      trustScore: 45,
      statusLegal: "Posesión",
      cargasLegales: "Certificado de posesión en trámite",
      impuestoPredial: 600,
      certificadoBusqueda: "Pendiente",
      comparisonMarket: -22.0,
      urbanServices: JSON.stringify({ agua: "Canal de riego", luz: "Poste cercano (150m)", desague: "No disponible", internet: "Sin cobertura" }),
      areaFront: 40,
      materialConstruccion: null,
      imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80"
      ]),
      features: JSON.stringify(["Riego por gravedad", "Acceso a Panamericana", "Suelo fértil", "Plusvalía proyectada"]),
      featured: false,
      active: true,
    },
    {
      title: "Departamento 2D - Miraflores",
      slug: "departamento-2d-miraflores",
      description: "Departamento de 85m² en 5to piso con vista al mar. 2 dormitorios, 1 baño, balcón. Edificio de 10 años con mantenimiento al día. Certificado de búsqueda negativo. Solo efectivo o hipoteca aprobada.",
      operationType: "venta",
      propertyType: "departamento",
      department: "Lima",
      province: "Lima",
      district: "Miraflores",
      address: "Av. Benavides 890, Miraflores",
      latitude: -12.1196,
      longitude: -77.0334,
      zone: "Residencial Miraflores",
      areaTotal: 85,
      areaBuilt: 85,
      price: 420000,
      precioM2: 4941.18,
      trustScore: 88,
      statusLegal: "Saneado",
      cargasLegales: "Hipoteca vigente (Banco de la Nación) - Saldar al cierre",
      impuestoPredial: 2400,
      certificadoBusqueda: "Negativo con salvedad hipotecaria",
      comparisonMarket: -5.0,
      urbanServices: JSON.stringify({ agua: "SEDAPAL", luz: "Luz del Sur", desague: "SEDAPAL", internet: "Múltiples proveedores" }),
      dormitorios: 2,
      banos: 1,
      estacionamiento: 1,
      pisos: 10,
      anoConstruccion: 2015,
      materialConstruccion: "concreto",
      imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"
      ]),
      features: JSON.stringify(["Vista al mar", "5to piso", "Balcón", "Cerca a Malecón"]),
      featured: true,
      active: true,
    },
    {
      title: "Terreno Industrial - Parcona",
      slug: "terreno-industrial-parcona-ica",
      description: "Terreno de 1500m² en zona industrial de Parcona. Cercado con muro de ladrillo. Acceso vehicular directo desde la Panamericana. Ideal para bodega o fábrica. Documentación en proceso de saneamiento.",
      operationType: "venta",
      propertyType: "terreno",
      department: "Ica",
      province: "Ica",
      district: "Parcona",
      address: "Panamericana Sur Km 300, Parcona",
      latitude: -14.0340,
      longitude: -75.7380,
      zone: "Zona Industrial Parcona",
      areaTotal: 1500,
      price: 195000,
      precioM2: 130,
      trustScore: 62,
      statusLegal: "En Trámite",
      cargasLegales: "Saneamiento en proceso (70% completado)",
      impuestoPredial: 900,
      certificadoBusqueda: "En trámite",
      comparisonMarket: -12.0,
      urbanServices: JSON.stringify({ agua: "Factible (pozo propio)", luz: "Transformador cercano", desague: "Tanque séptico", internet: "Claro 4G" }),
      areaFront: 25,
      materialConstruccion: null,
      imageUrl: "https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1581093458791-9d42e3c7e117?w=800&q=80"
      ]),
      droneVideoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      features: JSON.stringify(["Zona industrial", "Acceso directo Panamericana", "Cercado", "Pozo propio"]),
      featured: false,
      active: true,
    },
    {
      title: "Casa Familiar 4D - La Molina",
      slug: "casa-familiar-4d-la-molina",
      description: "Casa familiar de 300m² en terreno de 450m². 4 dormitorios, 3 baños, jardín amplio, estacionamiento para 3 autos. Construcción de 1998 con remodelaciones recientes. Saneado al 100%. Impuestos al día.",
      operationType: "venta",
      propertyType: "casa",
      department: "Lima",
      province: "Lima",
      district: "La Molina",
      address: "Av. Ramón Castilla 567, La Molina",
      latitude: -12.0733,
      longitude: -76.9459,
      zone: "Residencial La Molina",
      areaTotal: 450,
      areaBuilt: 300,
      price: 680000,
      precioM2: 2266.67,
      trustScore: 95,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas",
      impuestoPredial: 3600,
      certificadoBusqueda: "Negativo",
      comparisonMarket: 7.5,
      urbanServices: JSON.stringify({ agua: "SEDAPAL", luz: "Luz del Sur", desague: "SEDAPAL", internet: "Fibra óptica" }),
      dormitorios: 4,
      banos: 3,
      estacionamiento: 3,
      pisos: 2,
      anoConstruccion: 1998,
      materialConstruccion: "concreto",
      imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
        "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"
      ]),
      features: JSON.stringify(["Jardín amplio", "Piscina", "BBQ", "Cerca a colegios"]),
      featured: true,
      active: true,
    },
    {
      title: "Local Comercial Céntrico - Chincha Alta",
      slug: "local-comercial-centrico-chincha-alta",
      description: "Local comercial de 65m² en esquina céntrica de Chincha Alta. 2 plantas con baño completo. Ideal para oficina o tienda. Alta afluencia peatonal. Certificado de búsqueda sin observaciones. Alcabala calculada incluida.",
      operationType: "venta",
      propertyType: "local_comercial",
      department: "Ica",
      province: "Chincha",
      district: "Chincha Alta",
      address: "Jr. 28 de Julio 234, Chincha Alta",
      latitude: -13.4188,
      longitude: -76.1353,
      zone: "Centro Comercial Chincha",
      areaTotal: 65,
      areaBuilt: 65,
      price: 145000,
      precioM2: 2230.77,
      trustScore: 78,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas",
      impuestoPredial: 960,
      certificadoBusqueda: "Negativo",
      comparisonMarket: 1.5,
      urbanServices: JSON.stringify({ agua: "SEDACHIN", luz: "Luz Sur", desague: "SEDACHIN", internet: "Claro/TdP fibra" }),
      pisos: 2,
      anoConstruccion: 2005,
      materialConstruccion: "ladrillo",
      imageUrl: "https://images.unsplash.com/photo-1582037928769-181f2644ecb3?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1582037928769-181f2644ecb3?w=800&q=80"
      ]),
      features: JSON.stringify(["Esquina", "2 plantas", "Alta afluencia", "Cerca a bancos"]),
      featured: false,
      active: true,
    },
    {
      title: "Terreno Residencial - Pisco",
      slug: "terreno-residencial-pisco",
      description: "Terreno residencial de 200m² en urbanización privada de Pisco. Todos los servicios disponibles. Urbanización con vigilancia 24h. Documentación al día. Certificado de búsqueda negativo.",
      operationType: "venta",
      propertyType: "terreno",
      department: "Ica",
      province: "Pisco",
      district: "Pisco",
      address: "Urb. San Clemente Mz. 7 Lt. 12",
      latitude: -13.7116,
      longitude: -76.2044,
      zone: "Urb. San Clemente Pisco",
      areaTotal: 200,
      price: 62000,
      precioM2: 310,
      trustScore: 85,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas",
      impuestoPredial: 480,
      certificadoBusqueda: "Negativo",
      comparisonMarket: -3.0,
      urbanServices: JSON.stringify({ agua: "SEDAPISCO", luz: "Luz del Sur", desague: "SEDAPISCO", internet: "4G/HFC" }),
      areaFront: 10,
      materialConstruccion: null,
      imageUrl: "https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=800&q=80"
      ]),
      features: JSON.stringify(["Urbanización privada", "Vigilancia 24h", "Servicios completos", "Cerca a plaza"]),
      featured: false,
      active: true,
    },
    {
      title: "Oficina Ejecutiva - San Borja",
      slug: "oficina-ejecutiva-san-borja",
      description: "Oficina de 120m² en piso 8 con vista panorámica. 2 ambientes, baño privado, cocina. Edificio corporativo categoría A+. Estacionamiento incluido. Saneado, sin cargas. Impuesto predial incluido en mantenimiento.",
      operationType: "venta",
      propertyType: "oficina",
      department: "Lima",
      province: "Lima",
      district: "San Borja",
      address: "Av. Javier Prado Este 4600, San Borja",
      latitude: -12.1079,
      longitude: -76.9943,
      zone: "Corporativo San Borja",
      areaTotal: 120,
      areaBuilt: 120,
      price: 520000,
      precioM2: 4333.33,
      trustScore: 94,
      statusLegal: "Saneado",
      cargasLegales: "Sin cargas",
      impuestoPredial: 3200,
      certificadoBusqueda: "Negativo",
      comparisonMarket: 2.0,
      urbanServices: JSON.stringify({ agua: "SEDAPAL", luz: "Luz del Sur", desague: "SEDAPAL", internet: "Fibra óptica dedicada" }),
      dormitorios: 2,
      banos: 1,
      estacionamiento: 1,
      pisos: 15,
      anoConstruccion: 2020,
      materialConstruccion: "concreto",
      imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
      imageGallery: JSON.stringify([
        "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80"
      ]),
      features: JSON.stringify(["Piso 8", "Vista panorámica", "Categoría A+", "Cerca a Metro"]),
      featured: false,
      active: true,
    },
  ]

  for (const prop of properties) {
    await db.property.create({ data: prop })
  }

  console.log(`✅ Seeded ${properties.length} properties successfully`)
}

seed()
  .catch(console.error)
  .finally(() => db.$disconnect())
